// ═══════════════════════════════════════════════════════════════
//  snn_3input_weights.h
//  AUTO-GENERATED by train_snn_3input.py — DO NOT EDIT MANUALLY
//
//  3-Input Cardiac SNN: HR + SpO2 + HRV (ECG)
//  Architecture: 6 spike in → 8 hidden LIF → 4 output LIF
//  F1-macro: 0.5465 | Accuracy: 0.9048
// ═══════════════════════════════════════════════════════════════
#pragma once

// ── Architecture ─────────────────────────────────────────────
#define SNN3_N_IN    6   // 3 features × 2 directions
#define SNN3_N_HID   8
#define SNN3_N_OUT   4   // 4 classes
#define SNN3_T_STEPS 10

// ── LIF Hyperparameters ───────────────────────────────────────
#define SNN3_ALPHA     0.85f
#define SNN3_THRESHOLD 0.80f

// ── Spike Encoding Thresholds (medical ranges) ─────────────
//    Feature        Low    High
#define THR_HR_LOW    60.0f   // bpm
#define THR_HR_HIGH   100.0f
#define THR_SPO2_LOW  95.0f   // %
#define THR_SPO2_HIGH 100.0f
#define THR_HRV_LOW   30.0f   // ms
#define THR_HRV_HIGH  70.0f

// ── Class Names ────────────────────────────────────────────────
static const char* SNN3_CLASS_NAMES[4] = {
    "Normal", "Arrhythmia", "Hypotensive", "Hypertensive"
};

// ── Input→Hidden Weights [8][6] ──────────
static const float SNN3_W_IH[8][6] = {
    {-0.287033f, +0.667931f, +0.199473f, +0.122633f, +0.350538f, +0.188011f},
    {+0.493323f, +0.978169f, +0.437366f, -0.178806f, +0.537035f, -0.420174f},
    {+0.087718f, -0.021217f, -0.321260f, -0.169261f, +0.239150f, +0.306888f},
    {+0.663032f, +0.003330f, -0.402898f, -0.088770f, -0.428264f, -0.215942f},
    {+0.243412f, -0.243394f, +0.240632f, +0.084180f, -0.631029f, -0.584408f},
    {-0.326264f, -0.462132f, -0.122874f, -0.975908f, -0.098930f, +0.251534f},
    {+0.696057f, -0.203037f, -0.056028f, -0.718625f, -0.548882f, +0.736350f},
    {+0.025321f, +1.119802f, -0.448111f, -0.342220f, -0.660470f, -0.239526f}
};

// ── Hidden→Output Weights [4][8] ────────
static const float SNN3_W_HO[4][8] = {
    {-0.289709f, -0.859570f, +0.038341f, +0.547228f, +0.086571f, +0.342195f, +0.520200f, -0.204062f},
    {+0.002791f, +0.743886f, -0.223982f, -0.056640f, -0.229861f, -0.904293f, +0.350729f, -0.693436f},
    {+0.244943f, -0.370957f, +0.667046f, -0.426349f, +0.398701f, -0.116684f, -0.273690f, +0.083025f},
    {+0.337697f, +0.542928f, -0.046087f, +0.509538f, -0.105886f, -0.596596f, -0.477110f, -0.088392f}
};

// ── Hidden Biases [8] ────────────────────────────
static const float SNN3_B_H[8] = {-0.025005f, -0.198742f, -0.280536f, -0.041975f, +0.195809f, +0.573020f, +0.501181f, +0.111352f};

// ── Output Biases [4] ────────────────────────────
static const float SNN3_B_O[4] = {+0.891910f, +0.085414f, +0.456936f, -0.111918f};

// ═══════════════════════════════════════════════════════════════
//  SPIKE ENCODING — call this with raw sensor readings
// ═══════════════════════════════════════════════════════════════
static inline void snn3_encode_spikes(float hr, float spo2, float hrv,
                                       int spikes[SNN3_N_IN]) {
    spikes[0] = (hr   < THR_HR_LOW)    ? 1 : 0;  // HR too low
    spikes[1] = (hr   > THR_HR_HIGH)   ? 1 : 0;  // HR too high
    spikes[2] = (spo2 < THR_SPO2_LOW)  ? 1 : 0;  // SpO2 too low
    spikes[3] = (spo2 > THR_SPO2_HIGH) ? 1 : 0;  // SpO2 too high
    spikes[4] = (hrv  < THR_HRV_LOW)   ? 1 : 0;  // HRV too low
    spikes[5] = (hrv  > THR_HRV_HIGH)  ? 1 : 0;  // HRV too high
}

// ═══════════════════════════════════════════════════════════════
//  SNN INFERENCE — returns predicted class (0-3)
// ═══════════════════════════════════════════════════════════════
static inline int snn3_predict(float hr, float spo2, float hrv) {
    // 1. Spike encoding
    int spikes[SNN3_N_IN];
    snn3_encode_spikes(hr, spo2, hrv, spikes);

    // 2. LIF simulation over T timesteps
    float v_h[SNN3_N_HID] = {0};
    float v_o[SNN3_N_OUT] = {0};
    int   spike_counts[SNN3_N_OUT] = {0};

    for (int t = 0; t < SNN3_T_STEPS; t++) {
        // Hidden layer
        int s_h[SNN3_N_HID];
        for (int h = 0; h < SNN3_N_HID; h++) {
            float I = SNN3_B_H[h];
            for (int i = 0; i < SNN3_N_IN; i++) {
                I += SNN3_W_IH[h][i] * (float)spikes[i];
            }
            // LIF update with reset
            if (v_h[h] >= SNN3_THRESHOLD) v_h[h] = 0.0f;
            v_h[h] = SNN3_ALPHA * v_h[h] + I;
            s_h[h] = (v_h[h] >= SNN3_THRESHOLD) ? 1 : 0;
        }

        // Output layer
        for (int o = 0; o < SNN3_N_OUT; o++) {
            float I = SNN3_B_O[o];
            for (int h = 0; h < SNN3_N_HID; h++) {
                I += SNN3_W_HO[o][h] * (float)s_h[h];
            }
            if (v_o[o] >= SNN3_THRESHOLD) v_o[o] = 0.0f;
            v_o[o] = SNN3_ALPHA * v_o[o] + I;
            if (v_o[o] >= SNN3_THRESHOLD) spike_counts[o]++;
        }
    }

    // 3. Argmax over spike counts → predicted class
    int best_class = 0;
    int best_count = spike_counts[0];
    for (int o = 1; o < SNN3_N_OUT; o++) {
        if (spike_counts[o] > best_count) {
            best_count = spike_counts[o];
            best_class = o;
        }
    }
    return best_class;
}
